site_name: Graft.jl
site_description: Graph Toolkit for Julia
repo_url: https://github.com/pranavtbhat/Graft.jl

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- [index.md, Introduction]
- [generator.md     , Graph API , Generation     ]
- [combinatorial.md , Graph API , Combinatorial  ]
- [mutation.md      , Graph API , Mutation       ]
- [labelling.md     , Graph API , Labelling      ]
- [vdata.md         , Metadata  , Vertex Metadata]
- [edata.md         , Metadata  , Edge Metadata  ]
- [queries.md       , Query API , Query Macro    ]
- [hopgraph.md      , Query API , Hop Subgraphs  ]
- [graphio.md       , Graph IO  , File IO        ]
- [export.md        , Graph IO  , Export         ]
- [edgeiter.md      , Internal  , Edge Iteration ]
- [internal.md      , Internal  , Internal Docs  ]
